#!/bin/bash
# リリーススクリプト（冪等: 途中失敗しても再実行可能）
# Usage: ./scripts/release.sh [version]
#   version 省略時: パッチ番号を自動インクリメント (v0.3.1 → v0.3.2)
#
# フロー: PR作成 → CI待機 → マージ → mainにタグ → GitHub Actionsがリリース

set -euo pipefail

REPO="RyoheiHashimoto/pi-obd-meter"

# --- ヘルパー関数 ---

generate_pr_body() {
  local version="$1"
  local prev_tag="$2"
  local body="## Release $version"
  body+="\n"

  if [ -n "$prev_tag" ]; then
    body+="\n### Changes since $prev_tag\n\n"
    body+=$(git log "${prev_tag}..HEAD" --pretty=format:'- %s' --no-merges 2>/dev/null || echo "(変更ログ取得失敗)")
  else
    body+="\n### Changes\n\n"
    body+=$(git log --oneline -20 --pretty=format:'- %s' --no-merges 2>/dev/null || echo "(変更ログ取得失敗)")
  fi

  body+="\n\n---\n"
  body+="Auto-generated by \`make release\`"
  echo -e "$body"
}

# --- バージョン決定 ---

if [ -n "${1:-}" ]; then
  VERSION="$1"
else
  VERSION=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null | awk -F. '{print $1"."$2"."$3+1}')
fi

if [ -z "$VERSION" ]; then
  echo "Error: バージョンを決定できません。引数で指定してください (例: v0.1.0)"
  exit 1
fi

# semver 形式チェック
if ! echo "$VERSION" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "Error: バージョン形式が不正です: $VERSION (vX.Y.Z が必要)"
  exit 1
fi

echo "=== Release $VERSION ==="

# --- ブランチチェック ---

CURRENT=$(git branch --show-current)
if [ "$CURRENT" != "develop" ]; then
  echo "Error: release は develop ブランチで実行してください (現在: $CURRENT)"
  exit 1
fi

# リモートと同期チェック
git fetch origin develop main --quiet
LOCAL=$(git rev-parse develop)
REMOTE=$(git rev-parse origin/develop)
if [ "$LOCAL" != "$REMOTE" ]; then
  echo "Error: ローカルの develop が origin と異なります。git pull してください"
  exit 1
fi

# --- Step 1: タグの存在チェック ---

if git rev-parse "$VERSION" >/dev/null 2>&1; then
  echo "タグ $VERSION は既に存在します。リリース済みです。"
  exit 0
fi

# --- Step 2: PR作成 or 既存PR検出 ---

PREV_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo "")
PR_NUMBER=""

# 既存のオープンPRを探す
EXISTING_PR=$(gh pr list --head develop --base main --state open --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
  echo "既存のPR #${EXISTING_PR} を使用"
  PR_NUMBER="$EXISTING_PR"
  # PR本文を更新（バージョンが変わった可能性があるため）
  BODY=$(generate_pr_body "$VERSION" "$PREV_TAG")
  gh pr edit "$PR_NUMBER" --title "Release $VERSION" --body "$BODY"
  echo "PR #${PR_NUMBER} のタイトル・本文を更新"
else
  # マージ済みPRを確認（タグpushだけ失敗したケース）
  MERGED_TITLE=$(gh pr list --head develop --base main --state merged --json number,title --jq ".[0] | select(.title | contains(\"$VERSION\")) | .number" 2>/dev/null || echo "")
  if [ -n "$MERGED_TITLE" ]; then
    echo "PR #${MERGED_TITLE} は既にマージ済み。タグ作成に進みます"
    PR_NUMBER="$MERGED_TITLE"
  fi
fi

# PRが見つからない場合は新規作成
if [ -z "$PR_NUMBER" ]; then
  echo "PR 作成中 (develop → main)..."
  BODY=$(generate_pr_body "$VERSION" "$PREV_TAG")
  PR_URL=$(gh pr create --base main --head develop \
    --title "Release $VERSION" \
    --body "$BODY")
  PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
  echo "PR #${PR_NUMBER} 作成完了"
  echo "  $PR_URL"
fi

# --- Step 3: CI待機 + マージ ---

PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq '.state')
if [ "$PR_STATE" = "MERGED" ]; then
  echo "PR #${PR_NUMBER} は既にマージ済み"
else
  echo "CI 完了を待機中（必須チェックのみ）..."
  gh pr checks "$PR_NUMBER" --required --watch

  echo "マージ中..."
  gh pr merge "$PR_NUMBER" --merge --delete-branch=false
  echo "PR #${PR_NUMBER} マージ完了"
fi

# --- Step 4: mainにタグを付ける ---

echo "タグ作成中..."
git fetch origin main --quiet
git tag "$VERSION" origin/main
git push origin "$VERSION"

# develop にもマージコミットを取り込む
git pull origin develop --quiet

echo ""
echo "✓ $VERSION リリース完了"
echo "  GitHub Actions がリリースアセットを作成します"
echo "  https://github.com/${REPO}/releases/tag/${VERSION}"
